import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { serverSideTranslations } from "next-i18next/serverSideTranslations";
import { useTranslation } from 'next-i18next';
import { useRouter } from "next/router";

export async function getStaticProps({ locale }) {
  return {
    props: {
      ...(await serverSideTranslations(locale, [
        "common",
      ])),
    },
  };
}

export default function Home() {
  const { t, i18n } = useTranslation('common');
  const router = useRouter();

  function changeLang(lang) {
    router.push({
      pathname: `/${lang}`
    });
  }

  
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div style={{"color":"blue"}}>
          <div onClick={() => changeLang('en')}>en</div>
          <div onClick={() => changeLang('th')}>th</div>
        </div>
        <div>{t("animal.1")}</div>
        <div>{t("animal.2")}</div>
        <div>{t("animal.3")}</div>
      </main>
    </div>
  )
}
