import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { serverSideTranslations } from "next-i18next/serverSideTranslations";
import { useTranslation } from 'next-i18next';
import { useRouter } from "next/router";
import { useState, useEffect } from 'react';

export async function getStaticProps({ locale }) {
  return {
    props: {
      ...(await serverSideTranslations(locale, [
        "common",
      ])),
    },
  };
}

export default function Home() {
  const { t, i18n } = useTranslation("common");
  const router = useRouter();
  const { locale } = router;

  // useEffect(() => {
  //   handleChangeLanguage(locale, locale !== i18n.language ? true : false);
  // }, []);

  // const handleChangeLanguage = (lng, isReload) => {
  //   i18n.changeLanguage(lng);
  //   handleRoute(i18n.language);
  // };

  // const handleRoute = (locale) => {
  //   router.push(`${locale}${router.asPath}`, `${locale}${router.asPath}`, {
  //     locale: false,
  //   });
  // };



  console.log('before:', locale);


  function changeLang(lang) {
    router.push({
      pathname: `${lang}`  
    });
  }

  useEffect(() => {
    changeLang(locale);
  }, []);

  console.log('after:', locale);
  
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


      <main className={styles.main}>
        <div style={{"color":"blue"}}>
          <div onClick={() => changeLang('en')}>en</div>
          <div onClick={() => changeLang('th')}>th</div>
        </div>
        <div>{t("animal.1")}</div>
        <div>{t("animal.2")}</div>
        <div>{t("animal.3")}</div>
      </main>
    </div>
  )
}
